<footer>
    <div class="footer">
      <div class="body">
        <div class="footerlogo">
            <img src="Images/shieldlogo.png" alt="Vangarde Logo" class="footerlogoimg">
        </div>
        <div class="objfooter">
            <h3 style="margin-bottom: 15px">Contact</h3>
            <div class="link">
                <a href="https://kenkho.atlassian.net/jira/software/projects/GPC/summary">
                    Jira Project
                </a>
            </div>
            <div class="email">
                Email:
                <a href="mailto:Vangarde@gmail.com.au">Vangarde@gmail.com.au</a>
            </div>
            <div class="megaphonetelephone">
                <a>Tel:045-532-214</a>
            </div>
        </div>
        <div class="objfooter">
            <h3 style="margin-bottom: 15px">Company</h3>
            <div class="link">
                <a>
                    About us
                </a>
            </div>
            <div class="email">
                <a>Event </a>
            </div>
            <div class="megaphonetelephone">
                <a>Terms and conditions</a>
            </div>
        </div>
        <div class="objfooter">
            <h3 style="margin-bottom: 15px">Follow Us</h3>
            <div class="link">
                <a href="https://github.com/Kenneth-Khorin/Assignment1" target="_blank">GitHub</a>
            </div>
            <div class="email">
                <a>Instagram</a>
            </div>
            <div class="megaphonetelephone">
                <a>Twitter</a>
            </div>
        </div>
        </div>
        <hr>
        <div class="copyright">
        <p>&copy; 2025 Vangarde. All rights reserved.</p>
        </div>
    </div>
</footer>