<header>
        <nav role="navigation" aria-label="Main navigation">
            <ul>
                <li><a href="index.php" class="nav-link">Home</a></li>
                <li><a href="jobs.php" class="nav-link">Jobs</a></li>
                <li><a href="apply.php" class="nav-link">Apply</a></li>
                <li><a href="about.php" class="nav-link">About</a></li>
            </ul>
        </nav>
</header>